### ISSUE TITLE
[Bug] 로그인 하고 싶소.

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-07#150]
![로그인이 안돼](https://user-images.githubusercontent.com/31912670/70297730-8494d800-1832-11ea-870b-a163438da7bd.png)

**Comment by changicho** [comment]
어디서 감히 로그인을 하려고 하시나요!
개발자들만 로그인 가능합니다.

**Comment by 2ssue** [comment]
개발 버전이어서 아이디를 등록해야합니다. 혹시 해당 버그를 겪어 테스트를 하고 싶으신 분은 피키포키 팀에 팀의 이메일 하나를 알려주세요! 팀당 한 개씩 Host로 테스트할 수 있는 아이디를 등록해드리겠습니다~

**Comment by 2ssue** [comment]
네이버 아이디로 로그인 기능 검수를 마쳐 해당 이슈를 close 합니다. 감사합니다 🙏
