### ISSUE TITLE
[Player] 게임이 종료되었는데도 나갈때 에러가 뜹니다.

### ISSUE THREAD

**Issue by Johnie-Yeo** [connect-foundation/2019-07#155]
게임이 끝났으면 굳이 필요없는데 alert가 뜨네요
그리고 경고문구 내용도 좀 더 상세히 적으면 좋을것 같습니다.

**Comment by 2ssue** [comment]
Host가 방을 닫기 전 `beforeunload` 이벤트를 해제하지 않아 발생하는 이슈입니다.

다음 버전에 반영하도록 하겠습니다. 감사합니다!
