### ISSUE TITLE
방 이름을 지정할 수는 있는데 의미가 없어보입니다

### ISSUE THREAD

**Issue by suphremechicken** [connect-foundation/2019-07#156]
방장이 방을 생성할 때 쓴 방 이름이 다른 유져들한테 안보여요~ 

코드를 통해 방 입장하면, 방 안에서 방 제목이 무엇인지 보이면 좋을 것 같습니다.

**Comment by 2ssue** [comment]
방 이름은 Host가 방을 관리하기 위해서 만든 것이기 때문에, 유저에게 보여줄 필요가 없다고 판단되어 이번 버전에서는 반영하지 않았습니다. 의견 감사합니다.
