### ISSUE TITLE
[Player/Host] 게임 진행중 나타난 에러페이지

### ISSUE THREAD

**Issue by suphremechicken** [connect-foundation/2019-07#157]
### TypeError: Cannot read property 'score' of undefined
(anonymous function)
src/components/common/Dashboard.js:132
  129 | 
  130 | useEffect(() => {
  131 |   datas.sort(sortByHighScore);
> 132 |   const maxScore = datas[0].score;
   133 |   datas[0].order = 0;
  134 |   for (let index = 0; index < datas.length; index += 1) {
  135 |     const data = datas[index];

게임 진행중, 방원 한명이 나가고 나서 최종 점수 집계 페이지로 이동하려니 뜬 페이지???? 

정확하진 않습니다.

**Comment by ocy1011** [comment]
감사합니다 확인해볼게요

**Comment by 2ssue** [comment]
남은 Player가 없기 때문에, 결과로 빈 배열이 전송되어 생기는 이슈였습니다.  
랭킹 정보인 `data` 의 length가 0이어서 생겼던 이슈로 

1. 대기실에 아무도 없을 때 게임을 시작할 수 없도록 막는다.
2. 대시보드에 데이터가 없을 때 다른 디자인의 화면을 띄운다. 

의 방법으로 해결 될 예정입니다. 감사합니다!
