### ISSUE TITLE
일부 방번호는 입장이 불가능합니다

### ISSUE THREAD

**Issue by soyoungjeong** [connect-foundation/2019-07#158]
1 , 33 등 방번호를 생성하고 입장했을 때는 입장이 안되고
111111 으로 생성하고는 입장이 가능했습니다.

**Comment by 2ssue** [comment]
방 번호를 입력해서 생성하는 부분은 없는데 혹시 `1`, `33`은 방 이름을 말씀하시는건가요?

**Comment by soyoungjeong** [comment]
앗 넵 방이름입니다ㅎㅎ

**Comment by 2ssue** [comment]
방 이름은 Host가 퀴즈들을 관리하기 위해 부여하는 이름이고, 
게임 시작을 한 이후에 유저들이 입장할 수 있는 랜덤한 방 번호가 부여됩니다.

방 번호는 게임 시작을 누르고 임의로 부여되는 값인데 헷갈리셨을 수 있을 것 같네요 ㅠㅠ

좀 더 직관적으로 사용할 수 있으실만한 방법을 한번 고려해보겠습니다. 감사합니다!!
