### ISSUE TITLE
게임 실행중에 "유머" 문구가 나온후 에러가 발생했습니다.

### ISSUE THREAD

**Issue by GiPyoo** [connect-foundation/2019-07#212]
피키포키에 관심을 가져주셔서 감사합니다🤞

## 어떤 버그가 발생했나요?
> 참고할만한 이미지도 첨부해주시면 많은 도움이 될 거에요.😊
<img width="1082" alt="스크린샷 2019-12-13 오후 2 42 34" src="https://user-images.githubusercontent.com/44811887/70772140-f337df80-1db6-11ea-99ff-a24ff576460d.png">

### 버그의 발생 과정을 알려주세요
1. 방을 만든다
2. 문제를 만든다
3. 게임을 시작한다.
4. 시작되고 오류가 난다.

**Comment by 2ssue** [comment]
버그가 재현되지 않아 close 하겠습니다..
