### ISSUE TITLE
[ ux ] 기대했던 결과와 조금 다릅니다.

### ISSUE THREAD

**Issue by GiPyoo** [connect-foundation/2019-07#213]
피키포키에 관심을 가져주셔서 감사합니다🤞

## 어떤 버그가 발생했나요?
> 참고할만한 이미지도 첨부해주시면 많은 도움이 될 거에요.😊
게임 결과가 0개를 맞추었을 때 결과에 무언가 맞춘것 처럼 게이지가 올라가는 것이 부자연스러워 보입니다.
<img width="1142" alt="스크린샷 2019-12-13 오후 2 47 52" src="https://user-images.githubusercontent.com/44811887/70772789-faf88380-1db8-11ea-9b9a-ddcc7e5ef83e.png">

### 버그의 발생 과정을 알려주세요
1. 게임에 문제를 모두 틀린다.
2. 게임 결과를 확인한다.
### 예상했던 결과는 무엇이었나요?
0개를 맞추었을 경우 게이지가 차오르지 않는다.

**Comment by 2ssue** [comment]
0점일 때는 점수막대가 올라가지 않도록 변경하였습니다. 의견 감사합니다😊
![image](https://user-images.githubusercontent.com/42017052/71139522-bbff7d80-2251-11ea-8dd2-657146fec890.png)
