### ISSUE TITLE
3! 이름이 유효하지 않다고 합니다. 3 이 유효하지 않은지 !가 유효하지 않은지 잘 모르겠습니다. 

### ISSUE THREAD

**Issue by jominjimail** [connect-foundation/2019-07#214]
피키포키에 관심을 가져주셔서 감사합니다🤞

## 어떤 버그가 발생했나요?
> 참고할만한 이미지도 첨부해주시면 많은 도움이 될 거에요.😊
![image](https://user-images.githubusercontent.com/31717060/70772870-3004d600-1db9-11ea-9381-d712c0b783f5.png)

### 버그의 발생 과정을 알려주세요
1. Go to '...' 방번호를 입력하고 닉네임을 입력했습니다.
2. Click on '....' 확인을 눌렀습니다. 음 경고창이 뜨는걸 봤긴했지만, 너무 빨라 경고문을 다 읽지 못했습니다.

### 예상했던 결과는 무엇이었나요?
특수문자는 안된다는 말이 나올줄 알았습니다
경고창이 하단에 고정되어 있을줄 알았습니다.

**Comment by 2ssue** [comment]
특수 문자에 대한 입력을 막고, 입력했을 시 특수문자 입력이 불가능 하다는 안내 문구를 출력하도록 변경하였습니다. 감사합니다 🙏
