### ISSUE TITLE
키피포키 게임을 시작하면 너무나 하염없이 기다리는 것 같아요

### ISSUE THREAD

**Issue by Junow** [connect-foundation/2019-07#215]
피키포키에 관심을 가져주셔서 감사합니다🤞

## 어떤 버그가 발생했나요?
> 참고할만한 이미지도 첨부해주시면 많은 도움이 될 거에요.😊
![image](https://user-images.githubusercontent.com/32632221/70772828-1499cb00-1db9-11ea-80a1-2eb64f341003.png)
아무런 동작이 먹지 않습니다. ㅠㅠ
백그라운드에서 게임을 대기시킨다던지 하단에 로딩창을 작게 만들어 주시면 이쁠것 같아용

### 예상했던 결과는 무엇이었나요?
사람수가 1/3 2/3 3/3 처럼 올라가면서 게임 매칭이 될 줄 알았어요.
중간에 취소하는 버튼이 있었으면 좋겠어요.

**Comment by 2ssue** [comment]
Header에 뒤로가기 버튼을 만들어서 중단할 수 있도록 했습니다. 감사합니다😊
