### ISSUE TITLE
[bug] 입장 입력 창 길이 제한 필요

### ISSUE THREAD

**Issue by sukjae** [connect-foundation/2019-07#218]
피키포키에 관심을 가져주셔서 감사합니다🤞

## 어떤 버그가 발생했나요?
> 참고할만한 이미지도 첨부해주시면 많은 도움이 될 거에요.😊

![image](https://user-images.githubusercontent.com/8156543/70773547-18c6e800-1dbb-11ea-90e0-7e6e7d3838c1.png)

### 버그의 발생 과정을 알려주세요
1. 홈페이지 접속
2. 엄청 긴 방 이름 입력

### 예상했던 결과는 무엇이었나요?

에러없는 세상!

## 특이 사항이 있었다면 알려주세요!

get으로 요청 보내시는 것 같습니다. URL 길이가 제한 있는것으로 알고 있으니 , 입력창에 입력 가능한 최대 길이를 지정하면 좋을듯 하네요

**Comment by sukjae** [comment]
죄송해요 고장낸거같아요요..ㅠ

![image](https://user-images.githubusercontent.com/8156543/70773746-9f7bc500-1dbb-11ea-84c8-a8ce35011b34.png)

**Comment by sukjae** [comment]
아 괜찮네요 다행

**Comment by 2ssue** [comment]
입력창에 maxLength를 설정해 해결하였습니다. 감사합니다 🙏
