### ISSUE TITLE
대기중 방장이 나갈경우 참가자에게 안내

### ISSUE THREAD

**Issue by kgpyo** [connect-foundation/2019-07#219]
피키포키에 관심을 가져주셔서 감사합니다🤞

## 어떤 버그가 발생했나요?
> 참고할만한 이미지도 첨부해주시면 많은 도움이 될 거에요.😊

방을 생성하고, 참가자가 방에 참여를 하고 방장이 시작하기 버튼을 누루지 않고 나갈경우 참자가는 계속 기다리는 것 같습니다.

참가자도 방이 닫힌것을 확인할 수 있었으면 좋겠습니다.

### 버그의 발생 과정을 알려주세요
1. Go to '방을 생성한다.'
2. Click on '참자가자 해당 방에 들어간다'
3. Scroll down to '방장이 시작하기를 누르지 않고 나간다'

'참가자는 어떠한 안내를 받지 못함'

**Comment by 2ssue** [comment]
감사합니다. 
원래 됐던 기능인데 구조를 변경하면서 발생한 버그입니다 😢
발견해주셔서 정말 감사합니다.

**Comment by 2ssue** [comment]
문제를 해결하였습니다. 발견해주셔서 감사합니다. 🙏
