### ISSUE TITLE
점수가 0점인데 막대기가 올라가요

### ISSUE THREAD

**Issue by Junow** [connect-foundation/2019-07#220]
피키포키에 관심을 가져주셔서 감사합니다🤞

## 어떤 버그가 발생했나요?
> 참고할만한 이미지도 첨부해주시면 많은 도움이 될 거에요.😊
![image](https://user-images.githubusercontent.com/32632221/70773864-fa152100-1dbb-11ea-8d4d-35c98ef638c1.png)
0점인데 점수막대? 가 올라가요

### 버그의 발생 과정을 알려주세요
1. Go to 결과화면
2. Click on 
3. Scroll down to 
4. See error 0점인데 막대가 올라감

### 예상했던 결과는 무엇이었나요?
점수만큼 막대기가 증가하는 모션을 기대했어요

## 특이 사항이 있었다면 알려주세요!
점수막대가 올라가는 속도가 이쁘네요

___
#213 과 겹치는 이슈입니다.

**Comment by 2ssue** [comment]
0점일 때는 점수막대가 올라가지 않도록 변경하였습니다. 의견 감사합니다😊
![image](https://user-images.githubusercontent.com/42017052/71139522-bbff7d80-2251-11ea-8dd2-657146fec890.png)
