### ISSUE TITLE
글 작성해도 글이 올라가지 않습니다.

### ISSUE THREAD

**Issue by kgpyo** [connect-foundation/2019-07#221]
피키포키에 관심을 가져주셔서 감사합니다🤞

## 어떤 버그가 발생했나요?
> 참고할만한 이미지도 첨부해주시면 많은 도움이 될 거에요.😊
![image](https://user-images.githubusercontent.com/38881005/70773969-42344380-1dbc-11ea-921e-9b3be00d947c.png)

### 버그의 발생 과정을 알려주세요
1. Go to '채널이동.'
2. Click on '참가'
3. Scroll down to '여러번 대화 작성'

출력안됨

**Comment by 2ssue** [comment]
잘못 올리신거겠죠?

**Comment by 2ssue** [comment]
다른 프로젝트의 이슈로 이슈를 close합니다 🙏
