### ISSUE TITLE
방 list 페이지 제작

### ISSUE THREAD

**Issue by ocy1011** [connect-foundation/2019-07#33]
- [x] 페이지 구성
  - [x] 방 만들기 버튼
  - [x] 방 리스트
  - [x] 방 만들기 모달  

- [x] 방 만들기 로직
  - [x] 방 만들기 버튼을 누르면 방 만들기 모달 등장
  - [x] 방 만들기 모달에서 방 이름 입력
  - [x] 방 이름 입력 후 확인 버튼을 누르면 방 생성
  - [x] 생성된 방이 방 리스트에 추가

### 6주차 스프린트 기능 추가
- [x] 방 이름에 공백을 입력했을 때, 추가되지 않도록 한다.
- [x] 방 삭제 버튼을 만들고, 해당 방을 삭제했을 때 삭제되도록 한다.

관련 이슈: #162

**Comment by 2ssue** [comment]
### 6주차 스프린트 기능 추가
- [ ] 방 이름에 공백을 입력했을 때, 추가되지 않도록 한다.
- [ ] 방 삭제 버튼을 만들고, 해당 방을 삭제했을 때 삭제되도록 한다.
