### ISSUE TITLE
방 list 페이지 API 구현

### ISSUE THREAD

**Issue by ocy1011** [connect-foundation/2019-07#34]
방 생성 API 체크 사항
  - post 형태
  - [x] 방 이름에 대한 유효성 검사를 실시한다.
    - [x] 최대 26자까지 가능
    - [x] 한 Host는 동일한 방의 이름을 가질 수 없음
      > DB에서 userid + title에 대해 unique 설정을 해줘야함. client에서는 막았습니다.
  - [x] 유효성 검사를 통과할 경우 요청에 따른 새로운 방을 DB에 추가한다.
  - [x] 유효성 검사를 통과하지 못할 경우 에러메시지를 전송한다.

### 6주차 스프린트 추가 기능 구현
- [x] 기존에 존재하던 방을 삭제할 수 있다.
- [x] 방 이름에 대한 유효성 검사 추가
   - [x] 최소 1자 이상, 최대 26자 이하

관련 이슈: #162

**Comment by 2ssue** [comment]
### 6주차 스프린트 추가 기능 구현
- [ ] 기존에 존재하던 방을 삭제할 수 있다.
- [ ] 방 이름에 대한 유효성 검사 추가
   - [ ] 최소 1자 이상, 최대 26자 이하
