### ISSUE TITLE
퀴즈 편집 페이지 프론트엔드 구현

### ISSUE THREAD

**Issue by leecoders** [connect-foundation/2019-07#38]
- 헤더
  - [ ] 취소 버튼 클릭
  - 저장 버튼 클릭
    - [ ] 미완성된 템플릿이 있다면 "미완성된 퀴즈가 있으면 게임을 시작할 수 없습니다. 그대로 저장하시겠습니까?" 모달 -> 취소/저장
    - [ ] 전체 퀴즈 등록(서버로 전송)
- 네비게이션(작업 목록)
  - [ ] 등록된 퀴즈 대표 이미지 출력
  - [ ] 드래그 앤 드랍으로 순서 변경
  - [ ] 이미지 클릭 시 해당 퀴즈 상세 편집 화면 오른쪽 섹션에 출력
  - [ ] 이미지 오른쪽 상단 취소 버튼 클릭하여 등록된 퀴즈 삭제
  - 템플릿 추가 버튼 클릭
    - [ ] 클릭 시 템플릿 선택 모달
    - [ ] 취소/저장 버튼 클릭
- 섹션
  - N지 선다 항목 설정
    - [ ] 채워지지 않은 항목은 다르게 표현(색x, 체크박스x)
    - [ ] 각 항목의 오른쪽에 체크 박스(정답 체크 - 다중 체크 가능)
  - 문제 설명, 내용 추가
    - [ ] 타이틀 입력
    - [ ] 제한 시간 입력
    - [ ] 이미지 등록
    - [ ] 점수 입력

**Comment by 2ssue** [comment]
#123 에서 해결된 이슈로 이슈를 close 합니다.
