### ISSUE TITLE
닉네임 입력 페이지 url 통해 들어갔을 때 생기는 error 처리 필요

### ISSUE THREAD

**Issue by leecoders** [connect-foundation/2019-07#49]
### Issue
- 정상적인 로직으로는 `방 번호 입력 -> 닉네임 입력` 순서로 입장해야 하지만 url을 통해 시도할 수 있다.

### To do
- [ ] 닉네임 페이지 url을 통해 들어가면 첫 페이지로 redirect

**Comment by 2ssue** [comment]
#133 에서 처리된 이슈로 이슈를 close 합니다
