### ISSUE TITLE
게임 대기실 Player 페이지 구현

### ISSUE THREAD

**Issue by ocy1011** [connect-foundation/2019-07#6]
- [x] 로딩 이미지 애니메이션
- [x] 하단 닉네임 출력
- [x] Host가 게임 시작 신호를 보내면 카운트 다운

**Comment by 2ssue** [comment]
- [x] Host가 게임 시작 신호를 보내면 카운트 다운
  - 카운트 다운을 프로그래스바 형태로 구현하였음
