### ISSUE TITLE
점수 출력 화면 API

### ISSUE THREAD

**Issue by ocy1011** [connect-foundation/2019-07#81]
- [ ] 점수에 따른 순위 정렬
  -  점수를 기준으로 내림차순 정렬
  -  동점자가 있을 경우 글자를 기준으로 오름차순 정렬
  -  동점자는 공동 순위 적용

- [ ] 플레이어 개인 점수, 순위 전송
  - [ ] 플레이어에겐 개인 점수 순위 데이터를 전송한다.

**Comment by 2ssue** [comment]
#115 로 등록되어 처리된 이슈로 이슈를 close 합니다.
